services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: luib2006
      POSTGRES_DB: webslae
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  fastapi1:
    build: ./
    container_name: fastapi1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "true"  
    depends_on:
      - postgres
      - redis

  fastapi2:
    build: ./
    container_name: fastapi2
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: "false"  
    depends_on:
      - postgres
      - redis

  worker:
    build: ./
    command: celery -A app.api.v1.tasks.celery_app worker --loglevel=INFO --concurrency=1
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:luib2006@postgres:5432/webslae
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER: redis://redis:6379/1
      CELERY_BACKEND: redis://redis:6379/2
      MAX_COMPLEXITY: 10000000000000
      MAX_ESTIMATED_SECONDS: 3600
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi1
      - fastapi2

volumes:
  pgdata:
